<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Bootstrap Architect Plugin
    |--------------------------------------------------------------------------
    |
    | Whether to show the Architect plugin. Defaults to false in production.
    | Set this to true if you want to enable code generation in production,
    | though it's recommended to keep this disabled for security reasons.
    |
    | Environment Variable: ARCHITECT_SHOW
    |
    */
    'show' => env('ARCHITECT_SHOW', false),

    /*
    |--------------------------------------------------------------------------
    | Default Generation Options
    |--------------------------------------------------------------------------
    |
    | Configure which files should be generated by default when creating a new
    | resource through the Architect wizard. These defaults can be overridden
    | per-resource in the wizard interface.
    |
    | Note: Migrations are always generated as they are core to the plugin.
    |
    | - generate_factory: Create model factory for testing and seeding
    | - generate_seeder: Create database seeder class
    | - generate_resource: Create complete Filament resource with CRUD pages
    |
    */
    'generate_factory' => env('ARCHITECT_GENERATE_FACTORY', true),
    'generate_seeder' => env('ARCHITECT_GENERATE_SEEDER', true),
    'generate_resource' => env('ARCHITECT_GENERATE_RESOURCE', true),

    /*
    |--------------------------------------------------------------------------
    | Models Namespace
    |--------------------------------------------------------------------------
    |
    | The default namespace for generated Eloquent models. This determines
    | where your model classes will be created when using the Architect wizard.
    |
    */
    'namespace' => 'App\\Models',

    /*
    |--------------------------------------------------------------------------
    | Factories Namespace
    |--------------------------------------------------------------------------
    |
    | The default namespace for generated model factories. This determines
    | where your factory classes will be created for testing and seeding.
    |
    */
    'factories_namespace' => 'Database\\Factories',

    /*
    |--------------------------------------------------------------------------
    | Seeders Namespace
    |--------------------------------------------------------------------------
    |
    | The default namespace for generated database seeders. This determines
    | where your seeder classes will be created for populating test data.
    |
    */
    'seeders_namespace' => 'Database\\Seeders',

    /*
    |--------------------------------------------------------------------------
    | Filament Resources Namespace
    |--------------------------------------------------------------------------
    |
    | The default namespace for generated Filament resources. This determines
    | where your resource classes (including pages and actions) will be created.
    |
    */
    'resources_namespace' => 'App\\Filament\\Resources',

];
